import "@radix-ui/themes/styles.css";

import { Container, Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Navbar";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";
import { auth } from "@/auth";
// import Footer from "./Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ItikafConnect",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const getsession = async () => {
    const session = await auth();
    return session;
  };
  let classLogin = "";
  const session = await getsession();
  if (session?.user === undefined) {
    console.log("session", session?.user);
    const arrClas = [
      "justify-center",
      "items-center",
      "h-full",
      "flex",
      "bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))]",
      "from-extra_light_gold",
      "to-light_gold",
    ];
    classLogin = arrClas.join(" ");
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryClientProvider>
          <AuthProvider>
            <Theme className={`${classLogin}`}>
              {session?.user && <Navbar />}
              <main className="">
                <Container>{children}</Container>
              </main>
              {/* <Footer /> */}
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
