import "@radix-ui/themes/styles.css";

import { Container, Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Navbar";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";
import { auth } from "@/auth";
import Footer from "./Footer";
import Home from "./dashboard/page";
import { Toaster } from "@/components/ui/sonner";

// import Sidebar from "./Sidebar"; // Import Sidebar component

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ItikafConnect",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  let classLogin = "";
  if (!session?.user) {
    const arrClas = [
      "justify-center",
      "items-center",
      "h-full",
      "flex",
      "bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))]",
      "from-extra_light_gold",
      "to-light_gold",
    ];
    classLogin = arrClas.join(" ");
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <QueryClientProvider>
          <AuthProvider>
            <Theme className={`${classLogin}`}>
              {/* First child: Navbar, spans two columns */}
              {session?.user && (
                <div className="col-span-2">
                  <Navbar />
                </div>
              )}

              {/* Third child: Sidebar, second column of second row */}
              <div className="flex">
                {session?.user && (
                  <div className="hidden md:block h-[100vh] w-[300px]">
                    <Home />
                  </div>
                )}
                {/* Second child: Main content, first column of second row */}
                <main className="p-5 w-full md:max-w-[1140px]">
                  <Container>{children}</Container>
                </main>
              </div>
              {/* <div>
              </div> */}
            </Theme>
            <Footer />
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
